on:
  push:
  pull_request:
  schedule:
    - cron: '20 2 * * 1'

jobs:
  build-opm:
    container:
      image: freicon/opmbuild
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Git Repository
      uses: actions/checkout@v3
    - name: Check SOPM
      run: /usr/local/bin/opmbuild sopmtest $GITHUB_WORKSPACE/AuthHeader.sopm
    - name: build OPM
      run: /usr/local/bin/opmbuild build $GITHUB_WORKSPACE/AuthHeader.sopm
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: AuthHeader
        path: ${{ github.workspace }}/*.opm
        retention-days: 10
